name: 🚀 Deploy to FTP (Laravel + Vite)

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Stáhne repozitář
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ PHP prostředí (pro composer)
      - name: 🧰 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, bcmath, pdo, mysql
          coverage: none

      # 3️⃣ Node.js prostředí (pro Vite/Tailwind build)
      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 4️⃣ Nainstaluj PHP a JS závislosti + build
      - name: 🧱 Build Laravel (Composer + NPM)
        run: |
          composer install --no-dev --optimize-autoloader
          npm ci
          npm run build

      # 5️⃣ Nahraj na FTP
      - name: 🚀 Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /www/domains/zapichnito3d.cz/zolik/
          exclude: |
            **/.git*
            **/node_modules/**
            **/storage/**
            .env
            .github/
            README.md
